# Generated by Django 5.0.6 on 2024-05-28 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
        ('events', '0002_initial'),
        ('users', '0006_alter_customuser_campus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='events',
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='campus.campus')),
                ('events', models.ManyToManyField(blank=True, related_name='user_events', to='events.event')),
            ],
        ),
    ]
