# Generated by Django 5.0.6 on 2024-05-28 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
        ('users', '0007_remove_customuser_campus_remove_customuser_events_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.campus'),
        ),
    ]
