# Generated by Django 5.0.6 on 2024-05-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='budget_amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='event',
            name='charges',
            field=models.FloatField(default=0.0, editable=False),
        ),
        migrations.AddField(
            model_name='event',
            name='slots',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='event',
            name='total_budget_amount',
            field=models.FloatField(default=0.0),
        ),
    ]
