# Generated by Django 5.0.6 on 2024-05-21 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campus', '0001_initial'),
        ('events', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendees',
            field=models.ManyToManyField(blank=True, related_name='event_attendees', to='users.customuser'),
        ),
        migrations.AddField(
            model_name='event',
            name='campus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='campus.campus'),
        ),
        migrations.AddField(
            model_name='event',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_creator', to='users.customuser'),
        ),
    ]
