# Generated by Django 5.0.6 on 2024-05-28 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='initials',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
